#!/usr/bin/env bash
# ufw commands used to block all incoming traffic except SSH, HTTP, and HTTPS
sudo apt update
sudo apt install -y ufw
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw enable
sudo afw status verbose
sudo apt install -y telnet
