#!/usr/bin/env bash
# Configures nginx to add a custom X-Served-By header with the server's hostname
# shellcheck disable=SC2154
apt-get update -y
apt-get install -y nginx

echo "Holberton School for the win!" > /var/www/html/index.html

sed -i '/add_header X-Served-By/d' /etc/nginx/sites-available/default
# shellcheck disable=SC2016
sed -i '/server_name _;/a\        add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

service nginx start || service nginx restart
