#!/usr/bin/env bash
# Ensure nginx is installed, the default site is properly enabled, and nginx is running
apt-get update -y
apt-get install -y nginx
rm -f /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
