#!/usr/bin/env bash
# Configures nginx with a custom 404 page containing "Ceci n'est pas une page"
apt-get update -y
apt-get install -y nginx

echo "Holberton School for the win!" > /var/www/html/index.html

echo "Ceci n'est pas une page" > /var/www/html/404.html

sed -i '/redirect_me/d' /etc/nginx/sites-available/default
sed -i '/listen 80 default_server;/a\        rewrite ^/redirect_me/?$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

sed -i '/error_page 404/d' /etc/nginx/sites-available/default
sed -i '/server_name _;/a\        error_page 404 /404.html;' /etc/nginx/sites-available/default

service nginx start || service nginx restart
